let ContainerIdList = KubePodInventory
| where Name contains "hearing-results-document-subscription"
| where Name !contains "dbsetup"
| distinct ContainerID;
ContainerLog
| where ContainerID in (ContainerIdList)
| where LogEntry contains 'handleError unexpected error on'
| extend LogJson = parse_json(LogEntry)
| extend Queue = extract(@'handleError unexpected error on (\S+) moving to DLQ', 1, tostring(LogJson.message))
| summarize Count = count() by Queue, Day = bin(TimeGenerated, 1d)
| order by Day asc, Queue asc
