let ContainerIdList = KubePodInventory
| where Name startswith "hearing-results-document-subscription"
| where Name !contains "dbsetup"
| where ContainerName == "springboot-app"
| distinct ContainerID;
ContainerLog
| where ContainerID in (ContainerIdList)
| extend LogJson = parse_json(LogEntry)
| where tostring(LogJson.level) == "ERROR"
| where LogEntry contains "notifications.outbound"
    or LogEntry contains "Sending notification"
    or LogEntry contains "CallbackDeliveryService"
    or LogEntry contains "CallbackClient"
| project TimeGenerated, Level = tostring(LogJson.level), CorrId = tostring(split(tostring(LogJson["X-Correlation-Id"]), "-")[-1]), Message = tostring(LogJson.message)
| order by TimeGenerated desc
