let ContainerIdList = KubePodInventory
| where Name contains "hearing-results-document-subscription"
| where Name !contains "dbsetup"
| distinct ContainerID;
ContainerLog
| where ContainerID in (ContainerIdList)
| extend LogJson = parse_json(LogEntry)
| where tostring(LogJson.level) == "ERROR"
| where LogEntry contains "notifications.inbound"
    or LogEntry contains "handleMessage"
    or LogEntry contains "processInboundEvent"
    or LogEntry contains "NotificationService"
| project TimeGenerated, Level = tostring(LogJson.level), CorrId = tostring(split(tostring(LogJson["X-Correlation-Id"]), "-")[-1]), Message = tostring(LogJson.message)
| order by TimeGenerated desc
