let ContainerIdList = KubePodInventory
| where Name startswith "hearing-results-document-subscription"
| where Name !contains "dbsetup"
| where ContainerName == "springboot-app"
| distinct ContainerID;
ContainerLog
| where ContainerID in (ContainerIdList)
| where LogEntry contains 'PostStartup Database contains'
| extend LogJson = parse_json(LogEntry)
| project TimeGenerated, Level = tostring(LogJson.level), CorrId = tostring(split(tostring(LogJson["X-Correlation-Id"]), "-")[-1]), Message = tostring(LogJson.message)
| order by TimeGenerated desc
