let ContainerIdList = KubePodInventory
| where Name contains "hearing-results-document-subscription"
| where Name !contains "dbsetup"
| distinct ContainerID;
let correlationId = toscalar(
    ContainerLog
    | where ContainerID in (ContainerIdList)
    | where LogEntry contains "REPLACE_ME"
    | extend LogJson = parse_json(LogEntry)
    | project CorrelationId = tostring(LogJson["X-Correlation-Id"])
    | take 1
);
ContainerLog
| where ContainerID in (ContainerIdList)
| where LogEntry contains correlationId
| extend LogJson = parse_json(LogEntry)
| project TimeGenerated, Level = tostring(LogJson.level), CorrId = tostring(split(tostring(LogJson["X-Correlation-Id"]), "-")[-1]), Message = tostring(LogJson.message)
| order by TimeGenerated asc
