ContainerLogV2
| where PodName startswith "hearing-results-document-subscription"
| where ContainerName == "springboot-app"
| where LogMessage contains "failureCount:6"
| where LogMessage contains "notifications.inbound"
| extend LogJson = parse_json(LogMessage)
| project TimeGenerated, Level = tostring(LogJson.level), CorrId = tostring(split(tostring(LogJson["X-Correlation-Id"]), "-")[-1]), Message = tostring(LogJson.message)
| order by TimeGenerated asc
