ContainerLogV2
| where PodName startswith "hearing-results-document-subscription"
| where PodName !contains "dbsetup"
| where ContainerName == "springboot-app"
| extend LogJson = parse_json(LogMessage)
| where tostring(LogJson.level) == "ERROR"
| where LogMessage contains "notifications.inbound"
    or LogMessage contains "handleMessage"
    or LogMessage contains "processInboundEvent"
    or LogMessage contains "NotificationService"
| project TimeGenerated, Level = tostring(LogJson.level), CorrId = tostring(split(tostring(LogJson["X-Correlation-Id"]), "-")[-1]), Message = tostring(LogJson.message)
| order by TimeGenerated asc
