ContainerLogV2
| where PodNamespace == 'ns-prd-amp-01'
| where TimeGenerated > ago(14d)
| where ContainerName != 'istio-proxy'
| where PodName startswith 'hearing-results-document-subscription'
| where LogMessage contains 'getDocument request'
| make-series GetDocumentRequests = count() default=0
    on TimeGenerated
    from ago(14d) to now()
    step 1d
| mv-expand TimeGenerated, GetDocumentRequests
| extend TimeGenerated = todatetime(TimeGenerated), GetDocumentRequests = toint(GetDocumentRequests)
| render columnchart with (xcolumn=TimeGenerated, ycolumns=GetDocumentRequests, title="Get Document Requests per Day")
