ContainerLogV2
| where PodName contains "hearing-results-document-subscription"
| where PodName !contains "dbsetup"
| where ContainerName == "springboot-app"
| where LogMessage !contains "/health"
| extend LogJson = parse_json(LogMessage)
| extend IsJson = isnotempty(tostring(LogJson.message))
| project TimeGenerated,
    Level   = iif(IsJson, tostring(LogJson.level), "-"),
    CorrId  = iif(IsJson, tostring(split(tostring(LogJson["X-Correlation-Id"]), "-")[-1]), "-"),
    Message = iif(IsJson, tostring(LogJson.message), LogMessage)
| order by TimeGenerated asc
