ContainerLogV2
| where PodName contains "hearing-results-document-subscription"
| where PodName !contains "dbsetup"
| where LogMessage contains "Received notification request from Progression/HearingNows"
| extend LogJson = parse_json(LogMessage)
| project TimeGenerated, Level = tostring(LogJson.level), CorrId = tostring(split(tostring(LogJson["X-Correlation-Id"]), "-")[-1]), Message = tostring(LogJson.message)
| order by TimeGenerated asc
