ContainerLogV2
| where PodNamespace  == 'ns-dev-amp-01'
| where TimeGenerated > ago(12h)
| where ContainerName != 'istio-proxy'
| where PodName contains 'hearing-results-document-subscription'
| extend LogJson = parse_json(LogMessage)
| extend Message = tostring(LogJson.message)
| extend Level   = tostring(LogJson.level)
| extend LocalTime = datetime_utc_to_local(TimeGenerated, 'Europe/London')
| order by LocalTime desc
| take 500
| project
    ['LocalTime'] = format_datetime(LocalTime, 'yyyy-MM-dd HH:mm:ss'),
    Level,
    Message
