ContainerLogV2
| where PodNamespace  == 'ns-dev-amp-01'
| where TimeGenerated > ago(1d)
| where ContainerName != 'istio-proxy'
| where PodName startswith 'hearing-results-document-subscription'
| where LogMessage contains 'Received notification request'
| project TimeGenerated, LogLevel, LogMessage
| make-series ReceivedNotification = count() default=0
    on TimeGenerated
    from ago(1d) to now()
    step 1h
| render columnchart
