ContainerLogV2
| where PodNamespace  == 'ns-dev-amp-01'
| where TimeGenerated > ago(14d)
| where ContainerName != 'istio-proxy'
| where PodName startswith 'hearing-results-document-subscription'
| where LogMessage contains 'Received notification request'
| make-series ReceivedNotification = count() default=0
    on TimeGenerated
    from ago(14d) to now()
    step 1d
| mv-expand TimeGenerated, ReceivedNotification
| extend TimeGenerated = todatetime(TimeGenerated), ReceivedNotification = toint(ReceivedNotification)
| render columnchart with (xcolumn=TimeGenerated, ycolumns=ReceivedNotification, title="Received Notifications per Day")
