ContainerLogV2
| where PodNamespace  == 'ns-dev-amp-01'
| where TimeGenerated > ago(84d)
| where ContainerName != 'istio-proxy'
| where PodName contains 'hearing-results'
| where LogMessage contains 'Received notification request'
| project TimeGenerated, LogLevel, LogMessage
| make-series ReceivedNotification = count() default=0
    on TimeGenerated
    from ago(84d) to now()
    step 1d
| render timechart
